#+TITLE: GeoViQua feedback model - application guidelines

* Intro
** Purpose
   The application guidelines specify how we apply the feedback model
   within GeoViQua.  This document is one of several artifacts of the
   feedback model developed in Task 6.2.
** Boundary
   The feedback model is generally intended for user feedback, and
   producer feedback that is changing more rapidly than official
   metadata for which more quality cotrol is implied.

   The model is intended to connect GEOSS datasets and services to
   user data. User-centric information such as accounts and
   authentication and GEOSS concepts are therefore not represented
   directly, but are linked in at pre-defined junction points. These
   junction points are the user information and the target.

   While the model sometimes refers to ISO191xx schema elements, it is
   not intended to be seen as metadata or directly related to it. The
   ISO elements are included to ease interoperability in cases where a
   producer decides to include user-suggested data into the official
   metadata he maintains.
* Concepts
** Conceptual Model

The feedback model's main classes are
 - User information
 - Feedback group
 - Feedback item
 - Feedback focus
 - Feedback Target 

in rough order from user to the data set in question.

The user information contains self-asserted information about the user
which may be used to (assist in) qualifying the feedback he
produces. The model contains this class as a clear handover point to
the implemetation's user management, and to illustrate data an
implementation should know about its users.

A feedback group is a group of feedback items that "belong together",
i.e. a star rating and a comment which gives background
information. Whenever feedback is created, a feedback group is
created or extended.

The feedback item is an atomic instance of user feedback, for example,
a comment. Each item is associated to one or more foci, which qualify
the context of the item.

The target, associated with feedback over a focus, points to a data
set, resource, or something else which is pre-existent in the domain
of discourse. The target as contained in the model is geared towards
GEOSS resources.

A focus, on the other hand, may be created by the user who creates the
feedback item. A focus qualifies the feedback item, guided by one of
the three possible roles primary, secondary and supplementary.
  
** Feedback foci
   The feedback model relies on foci to associate feedback in a flexible
   way. This intends to increase discoverability by enabling
   to submit and discover focused feedback. Focuses are intended
   to be comparable to each other, resulting in a comparison results
   such as "identical", "overlapping" or "disjoint".

   In the following, the different types of focus are discussed.

*** Data-centric focus
    The data-centric focus qualifies the feedback within a data set.
    If it only refers to a target data set, i.e. without specifying
    layer or area constraints, then this is the canonical way to refer
    to the data set as a whole.

    If some of the elements are specified, then this is to be
    interpreted as to refer to the intersection of all the
    constraints.
*** Thematic focus
    A thematic foucs is used to qualify feedback that cannot be
    qualified by other means, or is not qulified implicitly or
    explicitly by the user. It just contains a title and can be
    regarded as a sort of free-form qualification of input.
*** Feedback focus
    The feedback focus qualifies feedback to pertain to other feedback.
    In the primary role, this states the feedback to be an answer to some
    other feedback in the system.
** Feedback focus roles
The primary focus ("the", i.e. exacly one) specifies the context of
the item, and points to the data set or resource the feedback is
about. Typically, all items in a feedback group have the same
primary focus.

A secondary focus says something about the nature of the feedback
item. For example, it may specify a certain domain of discourse in
which statements have to be understood.

A supplementary focus adds additional references, for example, another
region in another data set with similar problems. It is used to
formally model references that somehow are related to the feedback
item at hand, but does not imply that the feedback is relevant for the
referenced subject.

The following table summarizes the interpretation of feedback foci and
roles using hypothetic examples:

| Type/Role      | _primary_                | _secondary_                     | _supplementary_            |
| _Domain_       |                          | Domain feedback pertains to     | domains FB might relate to |
| _Thematic_     | A new discussion         | Title the user specifies        |                            |
| _Data-centric_ | Area an issue is located | Area used as a reference        | related dataset parts      |
| _Feedback_     | A direct reply           | other feedback being replied to | referenced feedback        |
| _Tag_          |                          | user-supplied tags              | autom. discovered tags     |
#+CAPTION: [Feedback type and roles]{Examples of interpreting the feedback types in different roles.}

* Use cases
  The application guidelines are intended to clarify how the model is
  to be applied. It is to become a "real" document, perhaps from input
  on this page. In the following, use cases and ther application is
  discussed.
** A domain-specific rating in the context of wheather forecasting
   - One feedback group containing one item
   - The one item is a rating
   - The primary focus of the rating is a unqualified data-centric focus
   - The secondary focus of the rating is a "wheather forecasting" domain focus
   - The targets of both foci refer to the data set in question
** A rating based on a part of the data
   This works as described for a domain-specific rating, except that
   only one focus, a data-centric focus, is needed.  It is then used
   to describe the part of the dataset the feedback is about.  If more
   than one "hotspot" is involved, these can be added as secondary
   foci.
** Justification for a rating
   This involves creating a feedback group with two items:
   - One user comment (the justification)
   - One rating
   Both should point to the data set in question using an identical
   primary focus. Otherwise, the description from the domain-specific
   rating applies.
** Add report in which the data set is intercompared
** Add a domain-specifc comment to a data set
** Search for comments pertaining to a domain
   This would work by first finding a URN within the applicable ontology,
   e.g. GEMET concepts.

   Then, all DominFocuses with the URN are identified and the feedback items
   which have the matching DomainFocus are being searched. This corresponds
   to a SQL join if the database schema is crafted carefully.

   To the user, the containing feedback groups may be of most interest as they
   group the feedback to the units in which it is intended to be understood.
* Constraints
  This section discusses constraints that (may) make sense within
  GeoViQua, but are not enforced at the conceptual model or XSD level.
** FB Group may not span datasets
   The primary foci of all items in a group may only target one
   dataset.  This seems sensible in general, but may need to be
   relaxed for certain use cases.
** Not more than one comment in a group
   This is a bit dependent on how large a feedback group makes sense. If we
   allow to extend feedback groups, e.g. to allow a group of people to submit
   feedback together, then this restriction is probably pointless.
** Require domain focus
   We could require one ore more domain foci to be added to each
   feedback item. With user accounts and sensible defaults this might lead
   to better qualified feedback.
* Diverse Issues
** Identifiers - uniqueness and canonicalization
   The target is not really intended to be defined within the
   model. Potentially the target should solve the problem of creating
   referenceable hierarchies and could be shared with other models,
   i.e. from a feedback perspective it merely establishes the context
   that really lives outside in GEOSS.

   It has been decided that, for the purpose of modelling feeback,
   the existence of a globally unique identifier for the referenced
   resources can be postulated.

   As far as we could determine, that is not the case within GEOSS.
   For prototyping and evaluation that may be acceptable, but later on
   there would need to exist a service of some kind which is capable
   of canonicalizing dataset identifiers.
** Identifiers - Granularity
   Not every feedback target can be assumed to have an identifier,
   because GEOSS datasets are of mixed granularity. As a result,
   targets need to be able to discern concepts that are accumulated at
   the granularity that can be identified using external identifers.

   For example, a dataset may be organized into layers which do not have
   a GEOSS identifier. To be able to target such a layer, the targets
   should be equipped with a locally (within the dataset) layer identifier
   (e.g. a name) and a parent target which contains the actual GEOSS
   identifier (possibly canonicalized).
** Default value recommendations
*** Domain
    The first user domain, if known, may be advertised as default
    in the UI for generating feedback. Thus, a default domain focus would be added
    which matches the user's background.
** Application domain ontology
   GEMET concepts seems a good candidate for a domain ontology, which would be
   used to properly identify relevant feedback. Also see the search comments
   use case.
* Summary
