* GeoViQua Feedback Model

This repository tracks the evolution of the GeoViQua feedback model,
also referred to as the consumer quality model.

* Development

The model itself is part of the GeoViQua EA models maintained by Joan Maso.
Here in this repository we (Simon Thum from Fraunhofer and who else contributes) track the feedback model as xmi, XSD schema, documentation and what else makes sense.

There are two noteable branches:
** raw branch
Here, raw generated EA output is tracked.
** cooked branch
In cooked, all subsequent edits are tracked to get from EA output
to a decent XSD. This increases the chance to keep current with the model
by frequently rebasing against raw.

This means it will be a pain (in the PITA sense) to follow this branch.
Use master instead, which is intended to be updated forward-only,
on major changes only.

** master branch
Not noteable, just the stable state. For the XSD, cooked is likely to be more current.
* Access
Github provides convenient access to current state and individual
changes to everyone via web, and you can clone the repository
even without a github account.

The Help pages of github explain everything in detail.

